name: Buil
on:
  workflow_dispatch: # allow manual run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v4
        with:
          repository: tanomin/mtphim
          ref: master
          token: ${{ secrets.REMOTE_REPO_ACCESS_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Cache pnpm dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: pnpm i

      - run: pnpm build


      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy to VPS
        env:
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: rsync -avz .next/ $VPS_USER@$VPS_HOST:/app/.next/
