name: Claim Banana
on:
  workflow_dispatch: # allow manual run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tanomin/mtphim
          ref: master
          token: ${{ secrets.REMOTE_REPO_ACCESS_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm i
